import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}  antialiased overflow-y-scroll body`}>
        <div className="max-w-[780px] p-4 md:p-10 mx-auto bg-background min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
